namespace                         = "personal"
region                            = "us-west-1"
project-name                      = "scout"
ssh_key                           = ""
consul-data-dir                   = "/mnt/consul/data/"
primary-cidr-block                = "172.18.0.0/16"
primary-subnet-public-cidr-block  = "172.18.16.0/24"
primary-subnet-private-cidr-block = "172.18.17.0/24"
